In [17]:
import pandas as pd

In [18]:
# The path to our CSV file
file = "health-protection-coverage.csv"

# Read our data into pandas
world_df = pd.read_csv(file)
world_df.head()

,Entity,Code,Year,Share of population covered by health insurance (ILO (2014)) (%)
0,Albania,ALB,2008,23.6
1,Algeria,DZA,2005,85.2
2,American Samoa,ASM,2009,3.0
3,Angola,AGO,2010,0.0
4,Antigua and Barbuda,ATG,2007,51.1

In [19]:
# Get a list of all of our columns for easy reference
world_df.columns

Index(['Entity', 'Code', 'Year',
       'Share of population covered by health insurance (ILO (2014)) (%)'],
      dtype='object')

In [20]:
# Identify incomplete rows
world_df.count()

Entity                                                              162
Code                                                                162
Year                                                                162
Share of population covered by health insurance (ILO (2014)) (%)    162
dtype: int64

In [21]:
# The Amount column is the wrong data type. It should be numeric.
world_df.dtypes

Entity                                                               object
Code                                                                 object
Year                                                                  int64
Share of population covered by health insurance (ILO (2014)) (%)    float64
dtype: object

In [22]:
world_df

,Entity,Code,Year,Share of population covered by health insurance (ILO (2014)) (%)
0,Albania,ALB,2008,23.6
1,Algeria,DZA,2005,85.2
2,American Samoa,ASM,2009,3.0
3,Angola,AGO,2010,0.0
4,Antigua and Barbuda,ATG,2007,51.1
5,Argentina,ARG,2009,96.8
6,Armenia,ARM,2009,100.0
7,Aruba,ABW,2003,99.2
8,Australia,AUS,2011,100.0
9,Austria,AUT,2010,99.3
10,Azerbaijan,AZE,2006,2.9
11,Bahamas,BHS,1995,100.0
12,Bahrain,BHR,2010,100.0
13,Bangladesh,BGD,2003,1.4
14,Barbados,BRB,1995,100.0
15,Belarus,BLR,2010,100.0
16,Belgium,BEL,2010,99.0
17,Belize,BLZ,2009,25.0
18,Benin,BEN,2009,9.0
19,Bhutan,BTN,2009,90.0
20,Bolivia,BOL,2009,42.7
21,Bosnia and Herzegovina,BIH,2004,59.2
22,Brazil,BRA,2009,100.0
23,Brunei,BRN,2010,100.0
24,Bulgaria,BGR,2008,87.0
25,Burkina Faso,BFA,2010,1.0
26,Burundi,BDI,2009,28.4
27,Cambodia,KHM,2009,26.1
28,Cameroon,CMR,2009,2.0
29,Canada,CAN,2011,100.0
...,...,...,...,...
132,South Africa,ZAF,2010,100.0
133,South Korea,KOR,2010,100.0
134,Spain,ESP,2010,99.2
135,Sri Lanka,LKA,2010,100.0
136,Sudan,SDN,2009,29.7
137,Swaziland,SWZ,2006,6.2
138,Sweden,SWE,2011,100.0
139,Switzerland,CHE,2010,100.0
140,Syria,SYR,2008,90.0
141,Taiwan,TWN,2010,99.6
142,Tajikistan,TJK,2010,0.3
143,Tanzania,TZA,2010,13.0
144,Thailand,THA,2007,98.0
145,Togo,TGO,2010,4.0
146,Tunisia,TUN,2005,80.0
147,Turkey,TUR,2011,86.0
148,Turkmenistan,TKM,2010,82.3
149,Uganda,UGA,2008,2.0
150,Ukraine,UKR,2011,100.0
151,United Arab Emirates,ARE,2011,100.0
152,United Kingdom,GBR,2010,100.0
153,United States,USA,2010,84.0
154,Uruguay,URY,2010,97.2
155,Uzbekistan,UZB,2010,100.0
156,Vanuatu,VUT,2010,100.0
157,Venezuela,VEN,2010,100.0
158,Vietnam,VNM,2010,61.0
159,Yemen,YEM,2003,42.0
160,Zambia,ZMB,2008,8.4
161,Zimbabwe,ZWE,2009,1.0

In [23]:
world_df.to_csv(r'healthcare_coverage.csv')